[project]
name = "dchu-waveform-sim"
version = "2.0.0"
requires-python = ">= 3.12"
dependencies = [
  "fastapi",
  "httpx",
  "pytest",
  "numpy",
  "scipy",
  "matplotlib",
  "latex2mathml",
  "sqlalchemy",
  "python-dotenv",
  "psycopg",
  "bcrypt",
]
authors = [
  {name = "Daniel Chu", email = "chudaniel400@gmail.com"}
]


[tool.vercel]
entrypoint = "app:app.py"
